# travis-ci integration for kiibohd/configurator

sudo:
  - false


language:
  - node_js


addons:
  apt:
    packages:
      - tree
      - build-essential
      - libudev-dev


# Versions of node.js to test
node_js:
  - "7"


# Specific Environment Variables
matrix:
  include:
  - os: linux
    env:
      - PACKAGE_OS=linux64
      - PACKAGE_NAME=kiibohd-configurator
      - PACKAGE_VERSION=$TRAVIS_TAG
      - PACKAGE_FULLNAME=$PACKAGE_NAME-$PACKAGE_VERSION
  - os: osx
    env:
      - PACKAGE_OS=macOS
      - PACKAGE_NAME=kiibohd-configurator
      - PACKAGE_VERSION=$TRAVIS_TAG
      - PACKAGE_FULLNAME=$PACKAGE_NAME-$PACKAGE_VERSION


# Package Setup
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree libusb; fi


# System setup
install:
  # Info about OS
  - uname -a

  # Directory tree to validate configurator.git
  - tree

  # Get version of node.js
  - npm --version

  # Get boot-cljs and show version
  - wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - chmod 755 boot
  - ./boot -V

  # Install electron and dependencies
  - npm install electron electron-rebuild --save-dev --save-exact
  - npm run res-install


# Build and packaging
script:
  # Build clojure target
  - ./boot prod-build

  # Example deployment file
  - mkdir -p output
  - touch output/$PACKAGE_FULLNAME-$PACKAGE_OS.tmp


# Deploy release
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  draft: true # XXX Must "publish" on github
  prerelease: true # XXX Set this to false to enable a stable release
  file_glob: true
  file: output/*
  on:
    tags: true
    repo: kiibohd/configurator


# Post test script commands
after_script:
  - tree output
  - tree target

