# appveyor integration for kiibohd/configurator

image: Visual Studio 2015


# Environment Variables
environment:
  PACKAGE_NAME: kiibohd-configurator
  matrix:
    - platform: x86
      PACKAGE_OS: win32
      nodejs_version: "7"
      ARCH: ia32
    - platform: x64
      PACKAGE_OS: win32
      nodejs_version: "7"
      ARCH: x64


configuration:
  - Release


# Commands run before cloning git repo
init:
  - git config --global core.autocrlf true

install:
  # Directory tree to validate configurator.git
  - Tree /F

  # Get version of node.js
  - ps: Install-Product node $env:nodejs_version
  - npm --version

  # Get boot-cljs and show version
  # No need to install python and nodejs as they are already handled
  - choco install boot-clj
  - boot -V

  # Install electron and dependencies
  - npm install
  - npm install -g node-pre-gyp
  - npm run res-install


# Build Commands
build_script:
  - boot prod-build

  # Example deployment file
  - mkdir -p output
  - touch output/%PACKAGE_NAME%-%APPVEYOR_REPO_TAG_NAME%-%PACKAGE_OS%.tmp

  # Build electron binary
  - ./node_modules/.bin/electron-packager target --platform=%PACKAGE_OS% --arch=%ARCH%


# Deployment Artifacts
artifacts:
  - path: output\%PACKAGE_NAME%-%APPVEYOR_REPO_TAG_NAME%-%PACKAGE_OS%.tmp
    name: tmp_artifact


# Deployment (tagged releases only)
deploy:
  # GitHub Releases
  - provider: GitHub
    auth_token:
      secure: vsCcKfR71BF5WWBmtzNzowpU96iPjuF3cD7yBdEySG0ku2svWAJRgdSj9je/He35
    draft: true
    prerelease: true
    description: 'Electron-based UI for configuring programmable keyboards designed by Input Club'
    artifact: tmp_artifact
    # Conditions for uploading release
    on:
      appveyor_repo_tag: true


# Post Build Commands
on_finish:
  - cd output
  - Tree /F

