# appveyor integration for kiibohd/configurator

image: Visual Studio 2015


environment:
  matrix:
    - nodejs_version: "7"
      GYP_MSVS_VERSION: 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015


platform:
  - x64
  - x86


configuration:
  - Release


# Commands run before cloning git repo
init:
  - git config --global core.autocrlf true

install:
  # Directory tree to validate configurator.git
  - Tree /F

  # Get version of node.js
  - ps: Install-Product node $env:nodejs_version
  - npm --version

  # Get boot-cljs and show version
  # No need to install python and nodejs as they are already handled
  - choco install boot-clj
  - boot -V

  # Install electron and dependencies
  - npm install electron electron-rebuild --save-dev --save-exact
  - npm install -g node-pre-gyp
  - npm run res-install


# Build Commands
build_script:
  - boot prod-build


# Post Build Commands
on_finish:
  - cd target
  - Tree /F

